robocopy c:\users\$Env:UserName\Documents\ s:\users\$Env:UserName\Documents\ /mir /xa:sh /xjd
robocopy c:\users\$Env:UserName\Pictures\ s:\users\$Env:UserName\Pictures\ /mir /xa:sh /xjd
robocopy c:\users\$Env:UserName\Videos\ s:\users\$Env:UserName\Videos\ /mir /xa:sh /xjd
robocopy c:\users\$Env:UserName\Desktop\ s:\users\$Env:UserName\Desktop\ /mir /xa:sh /xjd
pause
# SIG # Begin signature block
# MIIJOQYJKoZIhvcNAQcCoIIJKjCCCSYCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUHMwCaIcUzMvp3U0vPTXNJc+Y
# E7KgggatMIIGqTCCBJGgAwIBAgITeQAAAA96QLoMuctc9gAAAAAADzANBgkqhkiG
# 9w0BAQsFADA+MRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxFDASBgoJkiaJk/IsZAEZ
# FgRmaXJhMQ8wDQYDVQQDEwZGaXJhQ0EwHhcNMjQwMTIzMDIwOTQ4WhcNMjYwMTIz
# MDIxOTQ4WjAVMRMwEQYDVQQDEwpmaXJhIGFkbWluMIIBIjANBgkqhkiG9w0BAQEF
# AAOCAQ8AMIIBCgKCAQEAtyIWQreE8tjhILv9TBRDVi4xKdVo9d6pIrK+ILKykdIJ
# jPZ1VBw1a1VJzljNxtR9LJ3oZIbAVoiMuqxBI6KRUrrvP1evZzy4IeIoVIe6GknD
# NPA7Tif1uehWesWKMqkot9SFbD6mdWxqDvX6VOUh2q5QGN0DRt7+o1vFTjNVRCKK
# h41AmIA/NiawRGLWbR37DoPwZ5XFGiPUvXgEf7QHc8ei4BjV4qXjNCIKlBuXCFGl
# rsSOlPQ5Ew1jZX4RTJEW+izM1mjkJL4cl1vN8YXWxzrYKZYMrxD8bk2aEAAA44rX
# mzb5gDTngZx8fGf9wRuaX/2D0AdfRIZolheE1YzgZQIDAQABo4ICxzCCAsMwPQYJ
# KwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIhZPZG4bbpX6G6YEjhMHkUIat/1g2gsas
# KoSonBECAWQCAQIwEwYDVR0lBAwwCgYIKwYBBQUHAwMwDgYDVR0PAQH/BAQDAgeA
# MBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFCX6L8Iwx08k
# /02lkdnjhGZEIRryMB8GA1UdIwQYMBaAFDmt1POeQ3chFRq5EB85+Gesoj0UMIHD
# BgNVHR8EgbswgbgwgbWggbKgga+GgaxsZGFwOi8vL0NOPUZpcmFDQSxDTj1GSVJB
# REMyLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNl
# cyxDTj1Db25maWd1cmF0aW9uLERDPWZpcmEsREM9bG9jYWw/Y2VydGlmaWNhdGVS
# ZXZvY2F0aW9uTGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBv
# aW50MIG3BggrBgEFBQcBAQSBqjCBpzCBpAYIKwYBBQUHMAKGgZdsZGFwOi8vL0NO
# PUZpcmFDQSxDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2Vy
# dmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1maXJhLERDPWxvY2FsP2NBQ2VydGlm
# aWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MC8G
# A1UdEQQoMCagJAYKKwYBBAGCNxQCA6AWDBRmaXJhYWRtaW5AZmlyYS5sb2NhbDBP
# BgkrBgEEAYI3GQIEQjBAoD4GCisGAQQBgjcZAgGgMAQuUy0xLTUtMjEtMTM5NTE2
# MjMyNi0xNTc4NTMzMTQ5LTM1OTc4MzQ4ODQtMTE1MzANBgkqhkiG9w0BAQsFAAOC
# AgEAECk/MdprbI/WBedC6kiFur205rGaH9U+Lo+3GjcPuczuU2A4//YwsznETkn/
# dokc/VrOAYZup8l2gacWG/4e2IUOg6kExPTG9+L8bZXRzjqElRKt5FGn6Uz9c552
# VeQZ1w+MEaOzQdU26D7K9pEgkcxAUvcVYLiZqiyMAld1skwgn3O4GEIjglotSbqT
# gO1kmq8T/boajtYgMiLKqjk5siqKDM5UxGEZBsAZ/UXwJ0J2SLFhFEDl5loz4lg5
# odVDS9cb53h5/j1bL3vwfkJyxrHXdtpfALbV/LAMEaifaSYOkVD5bD8YQ8y2qsZM
# WPR+RHP8hrwlK3aygKpDXU+G8Tabv123406oY+9NhlCEP1oxJbC4BJpqpfl0iSxw
# /v/C4k8EMEacJ1KMyQm+fWa4OMCWqntGl18JHzVfgsx/a12qy9TZuAJ1aHTJyOnw
# pmXPM7unKmaKDw8I01Eers/sieJxDHEjrjgbAbmfPc/majs3ggXQNwCAuQpZSmPO
# fkhrabiMmX6O6IlZSM8vhWEQkUDdJL9KAhFjqviaTh2ZXkbc9lswx6MFM8EVdcW2
# hgwl3+Jet9u9wHFSl/Jy+TByt7T7GnLpNLZaqI3KRS7alu3yO8CHG1s4CxI5D+Sp
# 4+x9s4Zv2OU72QtibAlQg7SQRudoA0Iyrlhk3/7MvnJwJsYxggH2MIIB8gIBATBV
# MD4xFTATBgoJkiaJk/IsZAEZFgVsb2NhbDEUMBIGCgmSJomT8ixkARkWBGZpcmEx
# DzANBgNVBAMTBkZpcmFDQQITeQAAAA96QLoMuctc9gAAAAAADzAJBgUrDgMCGgUA
# oHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYB
# BAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0B
# CQQxFgQUksy0zizRQg4wiwxoCfxlqguQfwwwDQYJKoZIhvcNAQEBBQAEggEAB/Vf
# l/+BT/0TXjwxbP+nkYiwaMwFyZ/EMfvSM1PzGxh4IGpFO3/TS/qBySbiXTMauZPq
# ojh9XTsgiAYZRompwxuKO7ukQz3m7qldc6Fypby0QhlVC5mTmB1C96knHX7rLBQK
# RIgHPWbpi/5VR0q4AQzPGUQbOiuRxyTeOu8K8MqtOh1EvcHxLGC10r4CbYpmH1Qt
# eouckE0C9ODntxn4vYzZiBeQzcdLOouaxllSsYCMZ5C4OML4xb4o3bF3TqA8UB6J
# 8oC3MgCFWNQCraoLCNl47j6XIN4BqOzZUl1oPt7IQ8o+hS+pAgg7/NwoivonGv+T
# pv54qKg4Y4DdPcoyIA==
# SIG # End signature block
